### ISSUE TITLE
Gigasecond not working with Groovy 2.4.5?

### ISSUE THREAD

**Issue by ghajba** [exercism/xgroovy#29]
I am very new to Groovy and thought about learning it with Exercism.io. I have set-up an environment and did the first two exercises. The third one however seems not working.

I thought it was an error on my side or a bug in the `groovy.time.TimeCategory` module. So I looked at the example solution. Well, it is not working either:
`Test Failure: gigasecondFromDateWithHoursAndMinutes(GigasecondTest)
java.lang.AssertionError: expected:<Wed Mar 27 13:17:40 CET 1991> but was:<Wed Mar 27 14:17:40 CET 1991>`
`Test Failure: gigasecondFromDateWithHoursAndMinutesAndSeconds(GigasecondTest)
java.lang.AssertionError: expected:<Thu Feb 19 03:02:25 CET 2009> but was:<Thu Feb 19 04:02:25 CET 2009>`

There is one hour difference in these two tests. The third test works.

I run the tests on `Groovy Version: 2.4.5 JVM: 1.8.0_05 Vendor: Oracle Corporation OS: Windows 7`.

Can anyone verify the error or tell me what I do wrong?

**Comment by Dispader** [comment]
It's possible you aren't doing anything wrong— I don't remember the specific code which gave me problems, but I did run into some edge problems with the tests (I believe on Gigasecond) when working on [retrofitting them as Spock specifications](https://github.com/exercism/xgroovy/pull/31).

I don't know what the appetite is for the retrofit, but it seems to have some positive response.  If it doesn't, I can cycle back and try to firm up the existing Gigasecond tests.

**Comment by ghajba** [comment]
I have taken a look at your Gigasecond Spec. The expected values are the same as previously so it differs from what I get when I execute my code (or the example solution). And my difference is still +1 hour. Even with Groovy 2.4.7. Even when executing the code as a simple Groovy script.

The interesting is if I change the JVM property `user.timezone` from my current (CET) to UTC or GMT I get 3 test failures not just the two mentioned above.

**However** when I change the timezone to PST or CST it works fine. Can there be some time-calculation difference between these timezones which we are not aware of? Or can it be a Groovy issue?

**Comment by ghajba** [comment]
Well, I am closing this issue because it seems like a Groovy one and not related to exercism.
