### ISSUE TITLE
Add MIT LICENSE

### ISSUE THREAD

**Issue by rootulp** [exercism/xgroovy#41]
[README.md](https://github.com/exercism/xgroovy/blob/master/README.md) mentions the MIT license but there is no LICENSE file

**Comment by Dispader** [comment]
@kytrinyx Sorry to bug you (I know you're pretty busy), but— awkward question: is this an okay license to include for `xgroovy`.  I'd like to merge this, but I figured I'd check first because... it has your name on it.  To merge it without you seemed... rude?  😃

**Comment by kytrinyx** [comment]
Whuuut? I thought we already had the MIT license! Yes absolutely every single Exercism language track should be licensed under MIT and should have a `LICENSE` file.

**Comment by kytrinyx** [comment]
I always get it from here: https://choosealicense.com/licenses/mit/

**Comment by Dispader** [comment]
Fixed in f6ebde998b36a6218f9842359c0caee68f9f22a9 .  Thanks, all!
